[project]
name = "checkout-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-use>=0.11.9",
    "fastapi>=0.129.0",
    "langchain-anthropic>=1.3.3",
    "playwright>=1.58.0",
    "uvicorn>=0.41.0",
]
